<?php
/*-----------------------------------------------------------------------------+
| MagneticOne                                                                  |
| Copyright (c) 2008 MagneticOne.com <contact@magneticone.com>                 |
| All rights reserved                                                          |
+------------------------------------------------------------------------------+
| PLEASE READ  THE FULL TEXT OF SOFTWARE LICENSE AGREEMENT IN THE "license.txt"|
| FILE PROVIDED WITH THIS DISTRIBUTION. THE AGREEMENT TEXT IS ALSO AVAILABLE   |
| AT THE FOLLOWING URL: http://www.magneticone.com/store/license.php           |
|                                                                              |
| THIS  AGREEMENT  EXPRESSES  THE  TERMS  AND CONDITIONS ON WHICH YOU MAY USE  |
| THIS SOFTWARE   PROGRAM   AND  ASSOCIATED  DOCUMENTATION   THAT  MAGNETICONE |
| (hereinafter  referred to as "THE AUTHOR") IS FURNISHING  OR MAKING          |
| AVAILABLE TO YOU WITH  THIS  AGREEMENT  (COLLECTIVELY,  THE  'SOFTWARE").    |
| PLEASE   REVIEW   THE  TERMS  AND   CONDITIONS  OF  THIS  LICENSE AGREEMENT  |
| CAREFULLY   BEFORE   INSTALLING   OR  USING  THE  SOFTWARE.  BY INSTALLING,  |
| COPYING   OR   OTHERWISE   USING   THE   SOFTWARE,  YOU  AND  YOUR  COMPANY  |
| (COLLECTIVELY,  'YOU")  ARE  ACCEPTING  AND AGREEING  TO  THE TERMS OF THIS  |
| LICENSE   AGREEMENT.   IF  YOU    ARE  NOT  WILLING   TO  BE  BOUND BY THIS  |
| AGREEMENT, DO  NOT INSTALL OR USE THE SOFTWARE.  VARIOUS   COPYRIGHTS   AND  |
| OTHER   INTELLECTUAL   PROPERTY   RIGHTS    PROTECT   THE   SOFTWARE.  THIS  |
| AGREEMENT IS A LICENSE AGREEMENT THAT GIVES  YOU  LIMITED  RIGHTS   TO  USE  |
| THE  SOFTWARE   AND  NOT  AN  AGREEMENT  FOR SALE OR FOR  TRANSFER OF TITLE. |
| THE AUTHOR RETAINS ALL RIGHTS NOT EXPRESSLY GRANTED BY THIS AGREEMENT.       |
|                                                                              |
| The Developer of the Code is MagneticOne,                                    |
| Copyright (C) 2006 - 2010 All Rights Reserved.                               |
+-----------------------------------------------------------------------------*/

class Cart2cart_Localization_Countries
{
  private static $_countries = array(
    'AF' => array("AFG", "Afghanistan", 353),
    'AL' => array("ALB", "Albania", 13),
    'DZ' => array("DZA", "Algeria", 20),
    'AS' => array("ASM", "American Samoa", 0),
    'AD' => array("AND", "Andorra", 68),
    'AO' => array("AGO", "Angola", 350),
    'AI' => array("AIA", "Anguilla", 0),
    'AQ' => array("ATA", "Antarctica", 0),
    'AG' => array("ATG", "Antigua and Barbuda", 0),
    'AR' => array("ARG", "Argentina", 407),
    'AM' => array("ARM", "Armenia", 24),
    'AW' => array("ABW", "Aruba", 0),
    'AU' => array("AUS", "Australia", 0),
    'AT' => array("AUT", "Austria", 0),
    'AZ' => array("AZE", "Azerbaijan", 0),
    'BS' => array("BHS", "Bahamas", 0),
    'BH' => array("BHR", "Bahrain", 0),
    'BD' => array("BGD", "Bangladesh", 51),
    'BB' => array("BRB", "Barbados", 0),
    'BY' => array("BLR", "Belarus", 49),
    'BE' => array("BEL", "Belgium", 0),
    'BZ' => array("BLZ", "Belize", 0),
    'BJ' => array("BEN", "Benin", 0),
    'BM' => array("BMU", "Bermuda", 0),
    'BT' => array("BTN", "Bhutan", 0),
    'BO' => array("BOL", "Bolivia", 0),
    'BA' => array("BIH", "Bosnia and Herzegovina", 60),
    'BW' => array("BWA", "Botswana", 0),
    'BV' => array("BVT", "Bouvet Island", 0),
    'BR' => array("BRA", "Brazil", 0),
    'IO' => array("IOT", "British Indian Ocean Territory", 0),
    'BN' => array("BRN", "Brunei Darussalam", 0),
    'BG' => array("BGR", "Bulgaria", 64),
    'BF' => array("BFA", "Burkina Faso", 0),
    'BI' => array("BDI", "Burundi", 0),
    'KH' => array("KHM", "Cambodia", 0),
    'CM' => array("CMR", "Cameroon", 0),
    'CA' => array("CAN", "Canada", 0),
    'CV' => array("CPV", "Cape Verde", 0),
    'KY' => array("CYM", "Cayman Islands", 0),
    'CF' => array("CAF", "Central African Republic", 0),
    'TD' => array("TCD", "Chad", 0),
    'CL' => array("CHL", "Chile", 0),
    'CN' => array("CHN", "China", 82),
    'CX' => array("CXR", "Christmas Island", 0),
    'CC' => array("CCK", "Cocos (Keeling) Islands", 0),
    'CO' => array("COL", "Colombia", 0),
    'KM' => array("COM", "Comoros", 0),
    'CG' => array("COG", "Congo", 0),
    'CD' => array("COD", "Congo, The Democratic Republic Of The", 0),
    'CK' => array("COK", "Cook Islands", 0),
    'CR' => array("CRI", "Costa Rica", 0),
    'HR' => array("HRV", "Croatia", 101),
    'CU' => array("CUB", "Cuba", 0),
    'CY' => array("CYP", "Cyprus", 161),
    'CZ' => array("CZE", "Czech Republic", 103),
    'CI' => array("CIV", "Cote D'Ivoire (Ivory Coast)", 0),
    'DK' => array("DNK", "Denmark", 105),
    'DJ' => array("DJI", "Djibouti", 0),
    'DM' => array("DMA", "Dominica", 0),
    'DO' => array("DOM", "Dominican Republic", 0),
    'EC' => array("ECU", "Ecuador", 0),
    'EG' => array("EGY", "Egypt", 0),
    'SV' => array("SLV", "El Salvador", 0),
    'GQ' => array("GNQ", "Equatorial Guinea", 0),
    'ER' => array("ERI", "Eritrea", 0),
    'EE' => array("EST", "Estonia", 128),
    'ET' => array("ETH", "Ethiopia", 17),
    'FK' => array("FLK", "Falkland Islands  (Malvinas)", 0),
    'FO' => array("FRO", "Faroe Islands", 0),
    'FJ' => array("FJI", "Fiji", 0),
    'FI' => array("FIN", "Finland", 136),
    'FR' => array("FRA", "France", 139),
    'GF' => array("GUF", "French Guiana", 0),
    'PF' => array("PYF", "French Polynesia", 0),
    'TF' => array("ATF", "French Southern Territories", 0),
    'GA' => array("GAB", "Gabon", 0),
    'GM' => array("GMB", "Gambia", 0),
    'GE' => array("GEO", "Georgia", 0),
    'DE' => array("DEU", "Germany", 152),
    'GH' => array("GHA", "Ghana", 0),
    'GI' => array("GIB", "Gibraltar", 0),
    'GR' => array("GRC", "Greece", 0),
    'GL' => array("GRL", "Greenland", 0),
    'GD' => array("GRD", "Grenada", 0),
    'GP' => array("GLP", "Guadeloupe", 0),
    'GU' => array("GUM", "Guam", 0),
    'GT' => array("GTM", "Guatemala", 0),
    'GG' => array("GGY", "Guernsey", 0),
    'GN' => array("GIN", "Guinea", 0),
    'GW' => array("GNB", "Guinea-Bissau", 0),
    'GY' => array("GUY", "Guyana", 0),
    'HT' => array("HTI", "Haiti", 167),
    'HM' => array("HMD", "Heard and McDonald Islands", 0),
    'VA' => array("VAT", "Holy See (Vatican City State)", 0),
    'HN' => array("HND", "Honduras", 0),
    'HK' => array("HKG", "Hong Kong", 123),
    'HU' => array("HUN", "Hungary", 178),
    'IS' => array("ISL", "Iceland", 181),
    'IN' => array("IND", "India", 0),
    'ID' => array("IDN", "Indonesia", 189),
    'IR' => array("IRN", "Iran, Islamic Republic Of", 0),
    'IQ' => array("IRQ", "Iraq", 0),
    'IE' => array("IRL", "Ireland", 196),
    'IM' => array("IMN", "Isle of Man", 0),
    'IL' => array("ISR", "Israel", 170),
    'IT' => array("ITA", "Italy", 200),
    'JM' => array("JAM", "Jamaica", 0),
    'JP' => array("JPN", "Japan", 201),
    'JE' => array("JEY", "Jersey", 0),
    'JO' => array("JOR", "Jordan", 0),
    'KZ' => array("KAZ", "Kazakhstan", 220),
    'KE' => array("KEN", "Kenya", 123),
    'KI' => array("KIR", "Kiribati", 0),
    'KP' => array("PRK", "Korea, Democratic People's Republic Of", 232),
    'KR' => array("KOR", "Korea, Republic of", 0),
    'KW' => array("KWT", "Kuwait", 0),
    'KG' => array("KGZ", "Kyrgyzstan", 0),
    'LA' => array("LAO", "Lao People's Democratic Republic", 0),
    'LV' => array("LVA", "Latvia", 247),
    'LB' => array("LBN", "Lebanon", 0),
    'LS' => array("LSO", "Lesotho", 123),
    'LR' => array("LBR", "Liberia", 0),
    'LY' => array("LBY", "Libyan Arab Jamahiriya", 0),
    'LI' => array("LIE", "Liechtenstein", 0),
    'LT' => array("LTU", "Lithuania", 251),
    'LU' => array("LUX", "Luxembourg", 0),
    'MO' => array("MAC", "Macao", 0),
    'MK' => array("MKD", "Macedonia, the Former Yugoslav Republic Of", 264),
    'MG' => array("MDG", "Madagascar", 269),
    'MW' => array("MWI", "Malawi", 0),
    'MY' => array("MYS", "Malaysia", 270),
    'MV' => array("MDV", "Maldives", 0),
    'ML' => array("MLI", "Mali", 0),
    'MT' => array("MLT", "Malta", 272),
    'MH' => array("MHL", "Marshall Islands", 0),
    'MQ' => array("MTQ", "Martinique", 0),
    'MR' => array("MRT", "Mauritania", 0),
    'MU' => array("MUS", "Mauritius", 0),
    'YT' => array("MYT", "Mayotte", 0),
    'MX' => array("MEX", "Mexico", 0),
    'FM' => array("FSM", "Micronesia, Federated States Of", 0),
    'MD' => array("MDA", "Moldova, Republic of", 0),
    'MC' => array("MCO", "Monaco", 0),
    'MN' => array("MNG", "Mongolia", 0),
    'ME' => array("MNE", "Montenegro", 0),
    'MS' => array("MSR", "Montserrat", 0),
    'MA' => array("MAR", "Morocco", 0),
    'MZ' => array("MOZ", "Mozambique", 0),
    'MM' => array("MMR", "Myanmar", 66),
    'NA' => array("NAM", "Namibia", 0),
    'NR' => array("NRU", "Nauru", 0),
    'NP' => array("NPL", "Nepal", 307),
    'NL' => array("NLD", "Netherlands", 115),
    'AN' => array("ANT", "Netherlands Antilles", 0),
    'NC' => array("NCL", "New Caledonia", 0),
    'NZ' => array("NZL", "New Zealand", 0),
    'NI' => array("NIC", "Nicaragua", 0),
    'NE' => array("NER", "Niger", 0),
    'NG' => array("NGA", "Nigeria", 0),
    'NU' => array("NIU", "Niue", 0),
    'NF' => array("NFK", "Norfolk Island", 0),
    'MP' => array("MNP", "Northern Mariana Islands", 0),
    'NO' => array("NOR", "Norway", 321),
    'OM' => array("OMN", "Oman", 0),
    'PK' => array("PAK", "Pakistan", 458),
    'PW' => array("PLW", "Palau", 0),
    'PS' => array("PSE", "Palestinian Territory, Occupied", 0),
    'PA' => array("PAN", "Panama", 0),
    'PG' => array("PNG", "Papua New Guinea", 123),
    'PY' => array("PRY", "Paraguay", 0),
    'PE' => array("PER", "Peru", 0),
    'PH' => array("PHL", "Philippines", 123),
    'PN' => array("PCN", "Pitcairn", 0),
    'PL' => array("POL", "Poland", 349),
    'PT' => array("PRT", "Portugal", 350),
    'PR' => array("PRI", "Puerto Rico", 0),
    'QA' => array("QAT", "Qatar", 0),
    'RO' => array("ROU", "Romania", 360),
    'RU' => array("RUS", "Russian Federation", 364),
    'RW' => array("RWA", "Rwanda", 0),
    'RE' => array("REU", "Reunion", 0),
    'BL' => array("BLM", "Saint Barthélemy", 0),
    'SH' => array("SHN", "Saint Helena", 0),
    'KN' => array("KNA", "Saint Kitts And Nevis", 0),
    'LC' => array("LCA", "Saint Lucia", 0),
    'MF' => array("MAF", "Saint Martin", 0),
    'PM' => array("SPM", "Saint Pierre And Miquelon", 0),
    'VC' => array("VCT", "Saint Vincent And The Grenedines", 0),
    'WS' => array("WSM", "Samoa", 0),
    'SM' => array("SMR", "San Marino", 0),
    'ST' => array("STP", "Sao Tome and Principe", 0),
    'SA' => array("SAU", "Saudi Arabia", 0),
    'SN' => array("SEN", "Senegal", 0),
    'RS' => array("SRB", "Serbia", 0),
    'SC' => array("SYC", "Seychelles", 0),
    'SL' => array("SLE", "Sierra Leone", 0),
    'SG' => array("SGP", "Singapore", 0),
    'SK' => array("SVK", "Slovakia", 395),
    'SI' => array("SVN", "Slovenia", 396),
    'SB' => array("SLB", "Solomon Islands", 0),
    'SO' => array("SOM", "Somalia", 398),
    'ZA' => array("ZAF", "South Africa", 8),
    'GS' => array("SGS", "South Georgia and the South Sandwich Islands", 0),
    'ES' => array("ESP", "Spain", 407),
    'LK' => array("LKA", "Sri Lanka", 389),
    'SD' => array("SDN", "Sudan", 0),
    'SR' => array("SUR", "Suriname", 0),
    'SJ' => array("SJM", "Svalbard And Jan Mayen", 0),
    'SZ' => array("SWZ", "Swaziland", 0),
    'SE' => array("SWE", "Sweden", 415),
    'CH' => array("CHE", "Switzerland", 0),
    'SY' => array("SYR", "Syrian Arab Republic", 0),
    'TW' => array("TWN", "Taiwan, Province Of China", 0),
    'TJ' => array("TJK", "Tajikistan", 0),
    'TZ' => array("TZA", "Tanzania, United Republic of", 0),
    'TH' => array("THA", "Thailand", 428),
    'TL' => array("TLS", "Timor-Leste", 0),
    'TG' => array("TGO", "Togo", 0),
    'TK' => array("TKL", "Tokelau", 0),
    'TO' => array("TON", "Tonga", 437),
    'TT' => array("TTO", "Trinidad and Tobago", 0),
    'TN' => array("TUN", "Tunisia", 0),
    'TR' => array("TUR", "Turkey", 444),
    'TM' => array("TKM", "Turkmenistan", 0),
    'TC' => array("TCA", "Turks and Caicos Islands", 0),
    'TV' => array("TUV", "Tuvalu", 123),
    'UG' => array("UGA", "Uganda", 0),
    'UA' => array("UKR", "Ukraine", 453),
    'AE' => array("ARE", "United Arab Emirates", 0),
    'GB' => array("GBR", "United Kingdom", 0),
    'US' => array("USA", "United States", 123),
    'UM' => array("UMI", "United States Minor Outlying Islands", 0),
    'UY' => array("URY", "Uruguay", 0),
    'UZ' => array("UZB", "Uzbekistan", 0),
    'VU' => array("VUT", "Vanuatu", 0),
    'VE' => array("VEN", "Venezuela, Bolivarian Republic of", 0),
    'VN' => array("VNM", "Viet Nam", 462),
    'VG' => array("VGB", "Virgin Islands, British", 0),
    'VI' => array("VIR", "Virgin Islands, U.S.", 0),
    'WF' => array("WLF", "Wallis and Futuna", 0),
    'EH' => array("ESH", "Western Sahara", 0),
    'YE' => array("YEM", "Yemen", 0),
    'ZM' => array("ZMB", "Zambia", 0),
    'ZW' => array("ZWE", "Zimbabwe", 0),
    'AX' => array("ALA", "Aaland Islands", 0),
    'IC' => array("", "Canary Islands", 0),
    'YU' => array("YUG", "Yugoslavia", 0));

  public static function getCountries()
  {
    return self::$_countries;
  }
}